### ISSUE TITLE
netlify rewrite rule

### ISSUE THREAD

**Issue by plusgut** [ryhinchey/crank-realworld-example-app#2]
If you go to the article with pushstate it works perfectly. But if you reload said page it doesn't work anymore.
A url rewrite needs to happen.

If I'm not mistaken you are using netlify, therefore the config should add something like this:

```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

But be sure to put it after the api-proxy

**Comment by ryhinchey** [comment]
@plusgut many thanks!  your config worked perfectly.  I'm still new to netlify  - so this is much appreciated

**Comment by plusgut** [comment]
you're very welcome, I have a little note to that rewrite-rule though.
It will rewrite *everything*, even when you just want to load some javascript. If it doesn't find the file it will return the html with a status 200.

It would be preferably if a 404 comes for static files.

I would strongly suggest that you put every static file that you want to output, in a dedicated "static" directory. If you have something like that, then you can create a "rewrite-rule" to the same directory. If netlify finds that rule, the rewrite rules beneath it will not apply.
And if in the static file the file doesn't apply, it will return a 404.
Example: https://github.com/plusnew/plusnew-realworld/blob/master/netlify.toml

**Comment by plusgut** [comment]
oops i forgot to make a mention yesterday, sorry about that @ryhinchey
